### PR TITLE
add stars interoperabilty

### PR DESCRIPTION
**Pull request by btupper**
This PR adds expands the number of data types accepted by functions that consume/produce rasters to include [stars](https://r-spatial.github.io/stars/) class objects. The package adds one dependency (stars). A [copy of the first vignette](https://github.com/BigelowLab/tidysdm/wiki/a4_tidysdm_stars) demonstrates a stars-centric application.

### CODE REVIEW

**Comment by btupper** [comment]
Tests are updated and pass `devtools::check()` (and `devtools::install()`. But there is a snag - the conversion between `stars` and `SpatRaster` when a time dimension is involved required a modification by the `stars` author.  The [modification](https://github.com/r-spatial/stars/issues/717) works for the tidysdm application (as demonstrated by the successful tests) but it's only on the development branch for `stars`.  I don't know when it will be released on CRAN. R v4.4.2 to be released by the end of this month, and perhaps `stars` will be updated on CRAN then but I really don't know.  How you would like to proceed?

**Comment by dramanica** [comment]
We could make the `dev` branch dependent on the `dev` branch of `stars`, and then upload to CRAN once edzer has pushed the fix to CRAN.

**Comment by dramanica** [comment]
@btupper the tests seem to pass even though the CI uses the CRAN version of `stars`. What test did you expect to fail?

**Comment by btupper** [comment]
Well, that's a (happy) surprise!  The tricky bits are here...

[test_sample_pseudoabs_time](https://github.com/BigelowLab/tidysdm/blob/a3e97174ba0be1943b5ee503a7e8b663defa3eb4/tests/testthat/test_sample_pseudoabs_time.R#L101)

[test_thin_by_cell_time](https://github.com/BigelowLab/tidysdm/blob/a3e97174ba0be1943b5ee503a7e8b663defa3eb4/tests/testthat/test_thin_by_cell_time.R#L92)

**Comment by btupper** [comment]
Rats.  I just found a slightly different use case for `filter_collinear()` that fails when the `stars` object has a third dimension (it passes with just 2d).  I shall update that method and add a test. I have been trying as much as possible to simple cast from `stars` to `SpatRaster` to keep things simple, but that trick has its limits.  

It really is a bit like herding cats to manage the differences between the `stars` data model and the `SpatRaster/SpatRasterDataset` data model. It's probably a good exercise in improving mental acuity but it sure feels like a carnival fun house sometimes.

**Comment by dramanica** [comment]
Casting is always full of surprises, that's why tests are essential. Thanks for all the head work! Once we bring your changes in, it would be great to add your 'stars' vignette as an article to the 'tidysdm' website (obviously with the appropriate credits!), if you are happy with that.

**Comment by dramanica** [comment]
@btupper Great! Happy for me to merge in your changes?

**Comment by btupper** [comment]
Yes - please go ahead and merge when you are ready.  For clarity's sake, I am committed to supporting the `stars` implementation for the foreseeable future.

On a related issue, we had developed a tutorial we used for [Ocean Hack Week](https://oceanhackweek.org/ohw24/) on presence-only SDMs.  I have started to implement the same using `tidysdm` [here](https://bigelowlab.github.io/mola-mola/tidysdm-01.html). It's unfinished and a bit rough but I'll keep chipping away at it.  We are teaching a January-term class on SDMs, and our aspiration is to use `tidysdm`.

**Comment by btupper** [comment]
Hi @dramanica 

I'm preparing teaching materials using`tidysdm`.  The class begins in January.  I'm wondering about your thoughts on the timing of a CRAN update.  I can have the students install `tidysdm` from the `dev` branch on github, but my inner sloth prefers to use CRAN whenever possible.

**Comment by dramanica** [comment]
@btupper I doubt I'll get around to do a cran release before Christmas. But you can now install the dev version via runiverse, see the tidysdm website. It is very close to a cran install, just add the runiverse repo to the install.package command

**Comment by btupper** [comment]
OK, that works for me.  Thanks!

**Pull request merged**
